version: '3.7'
services:
  sampleapp:
    image: registry.${DOCKER_DOMAIN}/${REPO_NAME}:${TAG}
    networks:
      traefik: 
    deploy:
      replicas: "${DKR_REPLICA_COUNT:-1}"
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: ${DKR_RESTART_POLICY}
        delay: 10s
      labels:
        com.visualstudio.mrcooper.release-definition: ${RELEASE_DEFINITIONNAME}
        com.visualstudio.mrcooper.release-environment: ${RELEASE_ENVIRONMENTNAME}
        com.visualstudio.mrcooper.release-name: ${RELEASE_RELEASENAME}
        traefik.port: ${TRAEFIK_PORT}
        traefik.docker.network: ${TRAEFIK_NETWORK}
        traefik.backend: ${TRAEFIK_BACKEND}
        traefik.frontend.rule: Host:${TRAEFIK_FRONTEND_HOST}
        traefik.backend.loadbalancer.method: drr
        traefik.enable: 'true'
    logging:
      options:
        max-size: 50M
    environment:
    - SAMPLEENV=${SAMPLEENV}

networks:
  traefik:
    external:
      name: ${TRAEFIK_NETWORK}

