version: '3.7'
services:
  civicsense_students_be:
    image: ${APP_NAME}/${APP_TYPE}:${TAG}
    env_file: env_vars/${STAGE_NAME}.env
    environment:
      NODE_ENV: ${RELEASE_ENVIRONMENT}
      BUCKET_NAME: ${BUCKET_NAME}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRETACCESSKEY: ${SECRETACCESSKEY}
      APPLICATION_ARN: ${APPLICATION_ARN}
      REGION: ${REGION}
      COOKIE_NAME: ${COOKIE_NAME}
      SECRET: ${SECRET}
      MONGO_CONNECTION: ${MONGO_CONNECTION}
      REDIS_HOST: ${REDIS_HOST}
      OTP_URL: ${OTP_URL}
      OTP_AUTHKEY: ${OTP_AUTHKEY}
    ports:
      - "3000"
    networks:
      app:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      app:

networks:
  app:


