version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: "MongoDB" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "test@123"      
      MONGO_INITDB_DATABASE: "test"
    ports:
      - "27017:27019:27017:27019"
    volumes:
      - /opt/mongodb:/data/db
